# Generated by Django 3.2.8 on 2021-10-16 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=200, verbose_name='Имя района')),
                ('town', models.IntegerField(verbose_name='id города')),
            ],
        ),
        migrations.CreateModel(
            name='Education_1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('study_year', models.IntegerField(verbose_name='Учебный год')),
                ('school_type', models.CharField(choices=[('hight', 'Старшая'), ('middle', 'Средняя'), ('low', 'Младшая')], max_length=200, verbose_name='Тип школы')),
                ('school_name', models.CharField(max_length=200, verbose_name='Имя школы')),
                ('school_long', models.FloatField(verbose_name='longitude')),
                ('school_lat', models.FloatField(verbose_name='latitude')),
                ('students_num', models.PositiveIntegerField(verbose_name='количество студентов')),
                ('graduates_num', models.PositiveIntegerField(verbose_name='количество выпускников')),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.districts')),
            ],
        ),
    ]
