# Generated by Django 3.2.8 on 2021-10-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_1',
            name='school_type',
            field=models.CharField(choices=[('high', 'Старшая'), ('middle', 'Средняя'), ('low', 'Младшая')], max_length=200, verbose_name='Тип школы'),
        ),
    ]
